### ISSUE TITLE
Setup failed on creating Storage dir

### ISSUE THREAD

**Issue by jpecora716** [cr1st1p/k8s-on-lxd#6]
> sudo lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (lvm, btrfs, dir) [default=btrfs]: 
Create a new BTRFS pool? (yes/no) [default=yes]: 
Would you like to use an existing empty block device (e.g. a disk or partition)? (yes/no) [default=no]: 
Size in GB of the new loop device (1GB minimum) [default=30GB]: 
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=lxdbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
Would you like LXD to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 

> sudo ./k8s-on-lxd.sh -s
❗WARN:  It looks like SWAP is enabled on your system. Kubernetes might be unstable.
    You should disable it by running: sudo swapoff -a
    For more information, check https://github.com/kubernetes/kubernetes/issues/53533
    or try searching the net for: 'kubernetes swap'"
    This Kubernetes setup will not run the checks for the swap, but you run this at your own risk.
  INFO: checking nf_conntrack hashsize, via 'sudo' call
  INFO: Checking for 'dir' type storage
  INFO: Creating storage dir of type 'dir' from path /var/lib/lxd/disks/dir
Error: Source path '/var/lib/lxd/disks/dir' is within the LXD directory

This is my first time using lxd so maybe I misconfigured something?

**Comment by cr1st1p** [comment]
No, you did not configured LXD wrong.
I got the same error in a virtual machine, which is strange.

Until I find the reason and fix:
- the script k8s-on-lxd.sh is supposed to be run as your user and not as root (via sudo for example, like you did). When needed, for the setup part, it will run itself commands via sudo.
- create the 'dir' storage yourself. This means, create a directory somewhere your user can access and declare it as the source of a 'dir' storage pool. Like this:
`mkdir -p  $HOME/data/lxd-dir`
`lxc storage create dir dir source="$HOME/data/lxd-dir"`


- rerun the setup phase, but remember - without sudo.
`./k8s-on-lxd.sh -s`

**Comment by jpecora716** [comment]
Thanks, that got me a bit further.. I can't seem to get past "Sleeping 3 seconds to have the container get its IP..." now

Looks like it's most likely some weird lxd issue on my end.. Seems to be related to https://discuss.linuxcontainers.org/t/no-ipv4-on-arch-linux-containers/6395/32.. I'll dig in on my side. Thanks
